[package]
name = "lambda_test2"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_runtime = "0.14.0"
serde_json = "1.0.140"
tokio = "1.45.1"

# I'd just used cargo add lambda_runtime, cargo add ... etc., for installing those three dependencies
# (lambda_runtime, serde_json, tokio)